### ISSUE TITLE
Will the guice-validator work fine in Dropwizard?

### ISSUE THREAD

**Issue by imochurad** [xvik/guice-validator#4]
I am having hard time figuring out how to inject objects into my custom validator, that is running in Dropwizard? Do I need to do extra steps in order to get injections working in DW? Or what yoy have in README steps will work out of the box?

**Comment by xvik** [comment]
I did not understand what problem you have to "inject objects into my custom validator". Maybe it's about non guice managed validator.. but anyway I need more details.

As an example, here is how I usually register guice-validator

Validator guice module is created with dropwizard default validator:
```java
new ImplicitValidationModule(bootstrap().getValidatorFactory())
                .withMatcher(Matchers.not(Matchers.annotatedWith(Path.class)))
``` 
Of course, this module instance must be registered in guice (for example, in guicey using modules() method or with install() in other guice module).

Matcher is configured to avoid duplicate validation: resources validation is already configured in dropwizard and all other beans will be validated with guice aop (by guice-validator).

**Comment by imochurad** [comment]
```
import javax.inject.Inject;
import javax.validation.ConstraintValidator;
import javax.validation.ConstraintValidatorContext;
import javax.validation.Validator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DummyValidator implements ConstraintValidator<SendValidation, Dummy> {
	
	private static final Logger LOGGER = LoggerFactory.getLogger(SendValidator.class);
	
	@Inject
	private DummyVerificationHandler handler;
	
	@Inject
	private ApiConfiguration apiConfiguration;
	
	public DummyValidator() {
	}
	
	@Override
	public void initialize(SendValidation constraintAnnotation) {}

	@Override
	public boolean isValid(Dummy value, ConstraintValidatorContext context) {
		LOGGER.info(value + "");
		return true;
	}

}
```

the problem is that even though I am using guice-validator, Guice doesn't inject objects of type `DummyVerificationHandler` and  A`piConfiguration` into `DummyValidator`.

**Comment by xvik** [comment]
Hmm... you are right, there is a problem: dropwizard use validator which is not aware of guice and so custom validator is simply instantiated by default constraints factory. 

You can [see here](https://github.com/xvik/guice-validator/blob/master/src/main/java/ru/vyarus/guice/validator/AbstractValidationModule.java#L73) that guice aware constraint factory is assigned to dropwizard factory's context. Dropwizard uses the original factory to create non guice aware validator.

You can fix that by setting correct validator to the environment just after injector creation (dropwizard run phase, just before jersey start). I assume you're using guicey, but if not, solution will be essentially the same

```java
void run(configuration, environment) {
    environment.setValidator(InjectorLookup.getInjector(this).get().getInstance(Validator.class))
}
``` 

I will try it myself later and think if guice-validator must better support this case or, maybe, new ext module must be added to guicey for simplier integration.

**Comment by imochurad** [comment]
Regarding your fix, what `Validator` object will be set on `environment` in this case? 

In order this to work should I use both `dropwizard-guicy` and `guice-validator` ?

**Comment by imochurad** [comment]
I have found this suggestion here:
https://stackoverflow.com/questions/32179991/with-dropwizard-validation-can-i-access-the-db-to-insert-a-record/33107377?noredirect=1#comment76388521_33107377

But I think there should be more elegant solution to it..

**Comment by xvik** [comment]
No, you don't have to use dropwizard-guicey.. it was just an example (and assumption) because I don't know what are you using for guice integration.

guice-validator module (e.g. ImplicitValidationModule in my example above) creates Validator instance with  guice-enabled custom validators support. This instance is [bound to guice](https://github.com/xvik/guice-validator/blob/master/src/main/java/ru/vyarus/guice/validator/AbstractValidationModule.java#L76).

On the other hand, dropwizard creates its own Validator instance without guice-enabled validators support (default dropwizard validator). And that is your problem. To fix this you need to set correct validator inside environment just before jersey starts. Application run method is ideal for this.

My fix (above) simply obtains correct validator instance from guice context and sets it into environment. You should do the same `environment.setValidator(youInjector.getInstance(Valiator.class))`. This validator instance will be used during dropwizard server factory construction (for validation feature).. look `environment.getValidator()` usages in IDE.

**Comment by imochurad** [comment]
I am more inclined to use solution I have posted above in a stack over flow link.
And yes, I am using guicey. 
The only problem I have is for some reason `@Plugin` annotation doesn't seem to work as on start up I get Guice exception:

```
1) No implementation for java.util.Set<javax.validation.ConstraintValidator<?, ?>> was bound.
while locating java.util.Set<javax.validation.ConstraintValidator<?, ?>>
for the 1st parameter of com.salesforce.mhl.api.GuiceConstraintValidationFactory.<init>(GuiceConstraintValidationFactory.java:18)
at com.salesforce.mhl.api.ValidationModule.configure(ValidationModule.java:17)
```

this is how I register guicey bundle:
```
		bootstrap		     .addBundle(GuiceBundle.builder().enableAutoConfig(getClass().getPackage().getName())
		                .modules(new ApiModule(), new ValidationModule()).build());
```
And I also have a class that is annotated with `@Plugin(ConstraintValidator.class)`

Something minor is lacking here.

**Comment by imochurad** [comment]
Alright, so the problem was in generics.. but now I'm seeing this:

```
api_1                 | INFO  [2017-06-22 20:48:54,026] ru.vyarus.dropwizard.guice.module.installer.feature.plugin.PluginInstaller: plugins =
api_1                 |
api_1                 |     Set<ConstraintValidator>
api_1                 |         (com.salesforce.mhl.api.validation.SendValidator)
api_1                 |
api_1                 | Unable to create injector, see the following errors:
api_1                 |
api_1                 | 1) Tried proxying com.salesforce.mhl.api.GuiceConstraintValidationFactory to support a circular dependency, but it is not an interface.
api_1                 |   at com.salesforce.mhl.api.ValidationModule.configure(ValidationModule.java:17)
api_1                 |   while locating com.salesforce.mhl.api.GuiceConstraintValidationFactory
api_1                 |     for the 1st parameter of com.salesforce.mhl.api.ValidationModule.validator(ValidationModule.java:22)
api_1                 |   while locating javax.validation.Validator
api_1                 |     for field at com.salesforce.mhl.api.validation.SendValidator.javaxValidator(SendValidator.java:16)
api_1                 |   while locating com.salesforce.mhl.api.validation.SendValidator
api_1                 |   while locating javax.validation.ConstraintValidator annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=2, type=MULTIBINDER, keyType=)
api_1                 |   at com.salesforce.mhl.api.ApiModule.configure(ApiModule.java:35) (via modules: com.salesforce.mhl.api.ApiModule -> com.google.inject.multibindings.Multibinder$RealMultibinder)
api_1                 |   while locating java.util.Set<javax.validation.ConstraintValidator>
api_1                 |     for the 1st parameter of com.salesforce.mhl.api.GuiceConstraintValidationFactory.<init>(GuiceConstraintValidationFactory.java:18)
api_1                 |   at com.salesforce.mhl.api.ValidationModule.configure(ValidationModule.java:17)
api_1                 |   while locating com.salesforce.mhl.api.GuiceConstraintValidationFactory
```

**Comment by xvik** [comment]
Probably there is some misunderstanding. If you just want to use custom validators with guice injections inside them then all you have to do is set correct validator instance to the environment. Your custom validators will be obtained from guice context automatically (by [custom constraints factory](https://github.com/xvik/guice-validator/blob/master/src/main/java/ru/vyarus/guice/validator/AbstractValidationModule.java#L73)) when required.

If that's all you want then you don't need to use @Plugin at all.

**Comment by imochurad** [comment]
So, correct me if I am wrong:
1) I need to utilize guice-validator. In my module, I should run `install(new ValidationModule());`
2) In my app `run()` method I should put `environment.setValidator(InjectorLookup.getInjector(this).get().getInstance(Validator.class))`
3) I do not need guicey bundle in my codebase for custom validators to get members injected, is that right?

**Comment by xvik** [comment]
Yes

1. Use dropwizard validator factory to inherit dropwizard configurations: `install(new ValidationModule(bootstrap.getValidatorFactory()))`.
2. It is important to use correct validator with constraint factory overridden by guice-validator 
3. custom constraint factory will [handle guice support](https://github.com/xvik/guice-validator/blob/master/src/main/java/ru/vyarus/guice/validator/constraint/GuiceConstraintValidatorFactory.java#L28)

**Comment by imochurad** [comment]
Works fine, thanks a lot for your patience and guidance!

**Comment by xvik** [comment]
Glad to hear) I will look to add new guicey-ext module to simplify validator integration.

**Comment by imochurad** [comment]
Awesome, I'll be monitoring this thread for updates ;)
Thanks again!

**Comment by bjerne** [comment]
Would you maybe provide a code example?

**Comment by xvik** [comment]
I will add an example soon. Please track it in the guicey repo: https://github.com/xvik/dropwizard-guicey/issues/45.

I even started ext integration module but didn't finish it. I still plan to do it but not very soon.

**Comment by TK-999** [comment]
@xvik I was thinking that in a Dropwizard context, one could theoretically leverage the features of `dropwizard-guicey` to register `ConstraintValidator`s from scanned packages. Then the custom `ConstraintValidatorFactory` implementation could operate on a predetermined set of validator instances/classes, and delegate to the default `ConstraintValidatorFactory` provided by the environment in all other cases. This would have the advantage that guice would not manage the life cycle of default validators, of which there are likely to be more than custom ones. What do you think?

**Comment by xvik** [comment]
You actually don't need to "plug" anything in order to use your custom validation annotation: validator class is declared inside annotation. We can only change the way this custom validator (declared in  annotation) will be constructed: [guice validator factory](https://github.com/xvik/guice-validator/blob/master/src/main/java/ru/vyarus/guice/validator/constraint/GuiceConstraintValidatorFactory.java#L28) simply delegates instance creation to guice.

In context of dropwizard, we use pre-configured (by dropwizard) validator factory and apply custom (guice aware) constraint validator factory. The problem here is that now we have 2 validator factories: original (dw, not guice aware) and  [extended](https://github.com/xvik/guice-validator/blob/master/src/main/java/ru/vyarus/guice/validator/AbstractValidationModule.java#L72) used by guice (guice aware).

Guice creates validator from extended factory and so everything works as expected: custom validators are instantiated by guice.
Dropwizard creates validator with original factory and, as a result, we can't use custom annotations on resources (processed by dropwizard).

Current workaround is to change already created validator (so dropwizard could use correct validator for resources): 
```
environment.setValidator(InjectorLookup.getInjector(this).get().getInstance(Validator.class))
```

Ideally, this substitution should be automated with custom ext module, but I still not sure how to do it in an elegant way (without dirty hacks).

I may not completely understand what you mean, but I don't see anything else useful I could do (with custom installers, classpath scan or other guicey features).
